### ISSUE TITLE
Almost all tests fail

### ISSUE THREAD

**Issue by esfdk** [itu-bswu/RentIt#6] opened 2012-04-27 13:44 UTC
Exception: Initialization method RentIt.Tests.Scenarios.SystemAdmin.GetUsersTest.TestInit threw exception. System.Data.SqlClient.SqlException: System.Data.SqlClient.SqlException: Invalid column name 'genre'..

**Comment by esfdk** [comment] 2012-04-27 13:46
I think this has to do with the database changes? No idea how to fix it - fear I'll break more than I will fix.

**Comment by NiklasHansen** [comment] 2012-04-27 13:50
This is caused by database changes from Ulrik. But he haven't yet pushed the updated scripts and code. This has been going on since wednesday, so it should be fixed ASAP, Ulrik!

**Comment by ulrikdamm** [comment] 2012-04-27 13:53
Haven't yet gotten all the tests to pass locally, I'll look at is as soon as I can.

**Comment by esfdk** [comment] 2012-04-27 14:03
The tests that do not fail are the ones that do not inherit from Datatest (even though they should???).

**Comment by NiklasHansen** [comment] 2012-04-27 14:19
Can you provide a list of which test classes that don't inherit from DataTest, so Ulrik can include it in his commit?

**Comment by esfdk** [comment] 2012-04-27 14:29
LogoutScenarioTest.cs
LoginScenarioTest.cs
RentalHistoryScenarioTest.cs
BrowseNewestScenarioTest.cs
GenreScenarioTest.cs
MostDownloadedScenario.cs
are the ones I see

**Comment by NiklasHansen** [comment] 2012-05-14 14:32
These were fixed when Ulrik merged his Genre branch with develop and pushed it.

**Closed as completed by NiklasHansen** 2012-05-14 14:32 UTC
